

spring.application.name=appExamenSs
server.port=8080
spring.profiles.active=keycloak  # <-- AÑADE ESTO
logging.level.org.springframework.security=DEBUG
# ... resto de propiedades (base de datos, upload, etc.)

java -jar app.jar -Dspring.profiles.active=keycloak

spring.datasource.url=jdbc:mysql://localhost:3306/bd_examen_practico_hotelsito?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rio2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

file.upload-dir=uploads

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

