
keycloak.auth-server-url=http://localhost:8180
keycloak.realm=master
keycloak.resource=appExamenSs
keycloak.public-client=true
keycloak.principal-attribute=admin


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/hotel-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/hotel-realm/protocol/openid-connect/certs